
# Action to run build steps
name: "Build Steps"
description: "Run build steps for the project"
author: "Your Name <dsyme@github.com>"
runs:
  using: "composite" 

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/get-cmake@v3
      with:
        cmake-version: "3.25.0"

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release --parallel $(nproc)

    - name: Run tests
      run: ctest --test-dir build --output-on-failure --parallel $(nproc)